# Generated by Django 4.2.1 on 2023-05-10 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_remove_foodingredients_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='foodingredients',
            table='food_ingredients',
        ),
        migrations.AlterModelTable(
            name='foods',
            table='foods',
        ),
        migrations.AlterModelTable(
            name='ingredients',
            table='ingredients',
        ),
    ]
