# Generated by Django 4.2.1 on 2023-05-09 14:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_category_foods_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('price', models.PositiveIntegerField()),
                ('calories', models.PositiveIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='foods',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='category',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='FoodIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('mass', models.PositiveIntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.foods')),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='foods.ingredients')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
