# Generated by Django 4.2.1 on 2023-05-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_foods_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodingredients',
            name='amount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='foods',
            name='portions',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Порции'),
        ),
        migrations.AlterField(
            model_name='foodingredients',
            name='mass',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
