# Generated by Django 4.2.1 on 2023-05-10 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_category_table_alter_foodingredients_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categorie'},
        ),
        migrations.AlterModelOptions(
            name='foodingredients',
            options={'verbose_name': 'FoodIngredient'},
        ),
        migrations.AlterModelOptions(
            name='foods',
            options={'ordering': ['title'], 'verbose_name': 'Food'},
        ),
        migrations.AlterModelOptions(
            name='ingredients',
            options={'verbose_name': 'Ingredient'},
        ),
        migrations.RemoveField(
            model_name='foodingredients',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='foodingredients',
            name='ingredient',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='foods.ingredients'),
            preserve_default=False,
        ),
    ]
