# Generated by Django 4.2.1 on 2023-05-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_alter_foodingredients_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='calories',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
