"""Changed Permissions super model from BaseModel to TimedModel

Revision ID: 2895228a1bad
Revises: edcccf9cc464
Create Date: 2023-04-14 23:36:25.094924

"""
from alembic import op
import sqlalchemy as sa


revision = '2895228a1bad'
down_revision = 'edcccf9cc464'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('permissions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'updated_at')
    op.drop_column('permissions', 'created_at')
    # ### end Alembic commands ###
