"""Added tsvector to category

Revision ID: 3475183c1ad2
Revises: 7a6efd5903a7
Create Date: 2023-04-22 17:50:23.752823

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '3475183c1ad2'
down_revision = '7a6efd5903a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('ts_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('russian', name)", persisted=True), nullable=True))
    op.create_index('ix_category___ts_vector__', 'categories', ['ts_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_category___ts_vector__', table_name='categories', postgresql_using='gin')
    op.drop_column('categories', 'ts_vector')
    # ### end Alembic commands ###
