"""Added cart id

Revision ID: 3e190559676e
Revises: 96665c284537
Create Date: 2023-04-12 16:49:01.422323

"""
from alembic import op
import sqlalchemy as sa


revision = '3e190559676e'
down_revision = '96665c284537'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
