"""Not null to Optional field product_seller.seller_id

Revision ID: 469a2c81f0e0
Revises: ab85182e194c
Create Date: 2023-04-12 21:45:17.050145

"""
from alembic import op
import sqlalchemy as sa


revision = '469a2c81f0e0'
down_revision = 'ab85182e194c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_sellers', 'seller_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('sellers', 'name',
               existing_type=sa.VARCHAR(length=52),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sellers', 'name',
               existing_type=sa.VARCHAR(length=52),
               nullable=True)
    op.alter_column('product_sellers', 'seller_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
