"""Added Reviews.product_id

Revision ID: 4e300cea82ac
Revises: c6fd90578688
Create Date: 2023-03-26 19:20:58.665765

"""
from alembic import op
import sqlalchemy as sa


revision = '4e300cea82ac'
down_revision = 'c6fd90578688'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('product_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'reviews', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'product_id')
    # ### end Alembic commands ###
