"""Added tsvector to tags

Revision ID: 7a6efd5903a7
Revises: 7189e29bcf08
Create Date: 2023-04-22 17:28:24.358256

"""
from alembic import op
import sqlalchemy as sa


revision = '7a6efd5903a7'
down_revision = '7189e29bcf08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
