"""Remodeled whole database to fit into e-katalog idea

Revision ID: 89e1c50c8ac2
Revises: f5fa6797f660
Create Date: 2023-04-09 12:18:00.275996

"""
from alembic import op
import sqlalchemy as sa


revision = '89e1c50c8ac2'
down_revision = 'f5fa6797f660'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_sellers',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('seller_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('where', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('where_name', sa.String(length=52), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_sellers_id'), 'product_sellers', ['id'], unique=True)
    op.add_column('products', sa.Column('slug', sa.String(length=126), nullable=False))
    op.add_column('products', sa.Column('rating', sa.Integer(), nullable=False))
    op.drop_constraint('products_seller_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'seller_id')
    op.add_column('sellers', sa.Column('name', sa.String(length=52), nullable=True))
    op.drop_constraint('sellers_user_id_fkey', 'sellers', type_='foreignkey')
    op.drop_column('sellers', 'user_id')
    op.drop_column('sellers', 'bio')
    op.drop_constraint('users_seller_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'seller_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('seller_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_seller_id_fkey', 'users', 'sellers', ['seller_id'], ['id'])
    op.add_column('sellers', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('sellers', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('sellers_user_id_fkey', 'sellers', 'users', ['user_id'], ['id'])
    op.drop_column('sellers', 'name')
    op.add_column('products', sa.Column('seller_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('products_seller_id_fkey', 'products', 'sellers', ['seller_id'], ['id'], ondelete='CASCADE')
    op.drop_column('products', 'rating')
    op.drop_column('products', 'slug')
    op.drop_index(op.f('ix_product_sellers_id'), table_name='product_sellers')
    op.drop_table('product_sellers')
    # ### end Alembic commands ###
