"""CHanged rating type from int to float

Revision ID: ac8601a8d650
Revises: 3475183c1ad2
Create Date: 2023-04-23 13:05:12.910310

"""
from alembic import op
import sqlalchemy as sa


revision = 'ac8601a8d650'
down_revision = '3475183c1ad2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'rating',
                    existing_type=sa.FLOAT(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'rating',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
