"""Changed slug type

Revision ID: e3304d236843
Revises: 469a2c81f0e0
Create Date: 2023-04-12 22:15:15.978038

"""
from alembic import op
import sqlalchemy as sa


revision = 'e3304d236843'
down_revision = '469a2c81f0e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
