"""added parent_comment_id to comments

Revision ID: f5fa6797f660
Revises: 4e300cea82ac
Create Date: 2023-04-01 08:07:05.964394

"""
from alembic import op
import sqlalchemy as sa


revision = 'f5fa6797f660'
down_revision = '4e300cea82ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('parent_comment_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'comments', 'comments', ['parent_comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'parent_comment_id')
    # ### end Alembic commands ###
